### ISSUE TITLE
unity5.4.4p2客户端代码运行就闪退（已解决）

### ISSUE THREAD

**Issue by Prince-Ling** [GaoKaiHaHa/UnityLockStepDemo#1]
unity版本5.4.4p2
麻烦您告知下当前项目正在使用的版本

您能否留一个联系方式，
因为我正在调研帧同步相关的技术，有很多问题想向您请教

**Comment by Prince-Ling** [comment]
Unity5.5.0f3

**Comment by GaoKaiHaHa** [comment]
我的个人信息里就有我的联系方式啊，297496583@qq.com
