### ISSUE TITLE
服务端报错缺失引用

### ISSUE THREAD

**Issue by ghost** [GaoKaiHaHa/UnityLockStepDemo#11]

**Comment by Starscat1618** [comment]
![Uploading TIM截图20200210225516.png…]()

**Comment by Starscat1618** [comment]
![TIM截图20200210225516](https://user-images.githubusercontent.com/60499807/74163900-00aa0280-4c5e-11ea-8c12-bf406eaf03ff.png)

**Comment by fdgggy** [comment]
同问

**Comment by GaoKaiHaHa** [comment]
已补充哈
