### ISSUE TITLE
UnityLockStepDemo编译问题

### ISSUE THREAD

**Issue by bean-sprout1** [GaoKaiHaHa/UnityLockStepDemo#3]
这个项目本身就能编译通过吗，我获取下来编译不通过，是不是顺序不对，或有特点步骤
服务端用VS2017打开的
![image](https://user-images.githubusercontent.com/3314488/34516748-1f9ae078-f0b3-11e7-98a2-ced7078a8f63.png)
客户端端有unity5.6打开 VS2017编译的
![image](https://user-images.githubusercontent.com/3314488/34516792-44aa5984-f0b3-11e7-8135-6f2519457c5b.png)
麻烦帮忙解决下

**Comment by fdgggy** [comment]
同问

**Comment by GaoKaiHaHa** [comment]
已补充
